/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var user_pb = require('./user_pb.js');
goog.object.extend(proto, user_pb);
var commodity_pb = require('./commodity_pb.js');
goog.object.extend(proto, commodity_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.zbay.Order', null, global);
goog.exportSymbol('proto.zbay.PayInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.zbay.Order = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.zbay.Order, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.zbay.Order.displayName = 'proto.zbay.Order';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.zbay.PayInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.zbay.PayInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.zbay.PayInfo.displayName = 'proto.zbay.PayInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.zbay.Order.prototype.toObject = function(opt_includeInstance) {
  return proto.zbay.Order.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.zbay.Order} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zbay.Order.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    snapshot: (f = msg.getSnapshot()) && commodity_pb.Commodity.toObject(includeInstance, f),
    userId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    destination: (f = msg.getDestination()) && user_pb.Address.toObject(includeInstance, f),
    quantity: jspb.Message.getFieldWithDefault(msg, 5, 0),
    amount: jspb.Message.getFieldWithDefault(msg, 6, 0),
    status: jspb.Message.getFieldWithDefault(msg, 7, ""),
    comment: jspb.Message.getFieldWithDefault(msg, 8, ""),
    payInfo: (f = msg.getPayInfo()) && proto.zbay.PayInfo.toObject(includeInstance, f),
    expressNo: jspb.Message.getFieldWithDefault(msg, 13, ""),
    annotationsMap: (f = msg.getAnnotationsMap()) ? f.toObject(includeInstance, undefined) : [],
    created: (f = msg.getCreated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.zbay.Order}
 */
proto.zbay.Order.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.zbay.Order;
  return proto.zbay.Order.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.zbay.Order} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.zbay.Order}
 */
proto.zbay.Order.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 12:
      var value = new commodity_pb.Commodity;
      reader.readMessage(value,commodity_pb.Commodity.deserializeBinaryFromReader);
      msg.setSnapshot(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 4:
      var value = new user_pb.Address;
      reader.readMessage(value,user_pb.Address.deserializeBinaryFromReader);
      msg.setDestination(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setQuantity(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setAmount(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setComment(value);
      break;
    case 9:
      var value = new proto.zbay.PayInfo;
      reader.readMessage(value,proto.zbay.PayInfo.deserializeBinaryFromReader);
      msg.setPayInfo(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setExpressNo(value);
      break;
    case 10:
      var value = msg.getAnnotationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "");
         });
      break;
    case 11:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.zbay.Order.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.zbay.Order.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.zbay.Order} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zbay.Order.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSnapshot();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      commodity_pb.Commodity.serializeBinaryToWriter
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDestination();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      user_pb.Address.serializeBinaryToWriter
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getComment();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPayInfo();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.zbay.PayInfo.serializeBinaryToWriter
    );
  }
  f = message.getExpressNo();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getAnnotationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(10, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getCreated();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


Object.defineProperty(proto.zbay.Order.prototype, "id", {
  set: function(value) {
    this.setId(value);
  },
  get: function() {
    return this.getId();
  },
});


/**
 * optional string id = 1;
 * @return {string}
 */
proto.zbay.Order.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.zbay.Order.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


Object.defineProperty(proto.zbay.Order.prototype, "snapshot", {
  set: function(value) {
    this.setSnapshot(value);
  },
  get: function() {
    return this.getSnapshot();
  },
});


/**
 * optional Commodity snapshot = 12;
 * @return {?proto.zbay.Commodity}
 */
proto.zbay.Order.prototype.getSnapshot = function() {
  return /** @type{?proto.zbay.Commodity} */ (
    jspb.Message.getWrapperField(this, commodity_pb.Commodity, 12));
};


/** @param {?proto.zbay.Commodity|undefined} value */
proto.zbay.Order.prototype.setSnapshot = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.zbay.Order.prototype.clearSnapshot = function() {
  this.setSnapshot(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.zbay.Order.prototype.hasSnapshot = function() {
  return jspb.Message.getField(this, 12) != null;
};


Object.defineProperty(proto.zbay.Order.prototype, "userId", {
  set: function(value) {
    this.setUserId(value);
  },
  get: function() {
    return this.getUserId();
  },
});


/**
 * optional string userId = 3;
 * @return {string}
 */
proto.zbay.Order.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.zbay.Order.prototype.setUserId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


Object.defineProperty(proto.zbay.Order.prototype, "destination", {
  set: function(value) {
    this.setDestination(value);
  },
  get: function() {
    return this.getDestination();
  },
});


/**
 * optional Address destination = 4;
 * @return {?proto.zbay.Address}
 */
proto.zbay.Order.prototype.getDestination = function() {
  return /** @type{?proto.zbay.Address} */ (
    jspb.Message.getWrapperField(this, user_pb.Address, 4));
};


/** @param {?proto.zbay.Address|undefined} value */
proto.zbay.Order.prototype.setDestination = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.zbay.Order.prototype.clearDestination = function() {
  this.setDestination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.zbay.Order.prototype.hasDestination = function() {
  return jspb.Message.getField(this, 4) != null;
};


Object.defineProperty(proto.zbay.Order.prototype, "quantity", {
  set: function(value) {
    this.setQuantity(value);
  },
  get: function() {
    return this.getQuantity();
  },
});


/**
 * optional uint32 quantity = 5;
 * @return {number}
 */
proto.zbay.Order.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.zbay.Order.prototype.setQuantity = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


Object.defineProperty(proto.zbay.Order.prototype, "amount", {
  set: function(value) {
    this.setAmount(value);
  },
  get: function() {
    return this.getAmount();
  },
});


/**
 * optional uint64 amount = 6;
 * @return {number}
 */
proto.zbay.Order.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.zbay.Order.prototype.setAmount = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


Object.defineProperty(proto.zbay.Order.prototype, "status", {
  set: function(value) {
    this.setStatus(value);
  },
  get: function() {
    return this.getStatus();
  },
});


/**
 * optional string status = 7;
 * @return {string}
 */
proto.zbay.Order.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.zbay.Order.prototype.setStatus = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


Object.defineProperty(proto.zbay.Order.prototype, "comment", {
  set: function(value) {
    this.setComment(value);
  },
  get: function() {
    return this.getComment();
  },
});


/**
 * optional string comment = 8;
 * @return {string}
 */
proto.zbay.Order.prototype.getComment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.zbay.Order.prototype.setComment = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


Object.defineProperty(proto.zbay.Order.prototype, "payInfo", {
  set: function(value) {
    this.setPayInfo(value);
  },
  get: function() {
    return this.getPayInfo();
  },
});


/**
 * optional PayInfo payInfo = 9;
 * @return {?proto.zbay.PayInfo}
 */
proto.zbay.Order.prototype.getPayInfo = function() {
  return /** @type{?proto.zbay.PayInfo} */ (
    jspb.Message.getWrapperField(this, proto.zbay.PayInfo, 9));
};


/** @param {?proto.zbay.PayInfo|undefined} value */
proto.zbay.Order.prototype.setPayInfo = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.zbay.Order.prototype.clearPayInfo = function() {
  this.setPayInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.zbay.Order.prototype.hasPayInfo = function() {
  return jspb.Message.getField(this, 9) != null;
};


Object.defineProperty(proto.zbay.Order.prototype, "expressNo", {
  set: function(value) {
    this.setExpressNo(value);
  },
  get: function() {
    return this.getExpressNo();
  },
});


/**
 * optional string expressNo = 13;
 * @return {string}
 */
proto.zbay.Order.prototype.getExpressNo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.zbay.Order.prototype.setExpressNo = function(value) {
  jspb.Message.setProto3StringField(this, 13, value);
};


Object.defineProperty(proto.zbay.Order.prototype, "annotationsMap", {
  set: function(value) {
    this.setAnnotationsMap(value);
  },
  get: function() {
    return this.getAnnotationsMap();
  },
});


/**
 * map<string, string> annotations = 10;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.zbay.Order.prototype.getAnnotationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 10, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.zbay.Order.prototype.clearAnnotationsMap = function() {
  this.getAnnotationsMap().clear();
};


Object.defineProperty(proto.zbay.Order.prototype, "created", {
  set: function(value) {
    this.setCreated(value);
  },
  get: function() {
    return this.getCreated();
  },
});


/**
 * optional google.protobuf.Timestamp created = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.zbay.Order.prototype.getCreated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 11));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.zbay.Order.prototype.setCreated = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.zbay.Order.prototype.clearCreated = function() {
  this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.zbay.Order.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 11) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.zbay.PayInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.zbay.PayInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.zbay.PayInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zbay.PayInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    payResult: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.zbay.PayInfo}
 */
proto.zbay.PayInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.zbay.PayInfo;
  return proto.zbay.PayInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.zbay.PayInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.zbay.PayInfo}
 */
proto.zbay.PayInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPayResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.zbay.PayInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.zbay.PayInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.zbay.PayInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zbay.PayInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPayResult();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


Object.defineProperty(proto.zbay.PayInfo.prototype, "type", {
  set: function(value) {
    this.setType(value);
  },
  get: function() {
    return this.getType();
  },
});


/**
 * optional string type = 1;
 * @return {string}
 */
proto.zbay.PayInfo.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.zbay.PayInfo.prototype.setType = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


Object.defineProperty(proto.zbay.PayInfo.prototype, "payResult", {
  set: function(value) {
    this.setPayResult(value);
  },
  get: function() {
    return this.getPayResult();
  },
});


/**
 * optional string payResult = 2;
 * @return {string}
 */
proto.zbay.PayInfo.prototype.getPayResult = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.zbay.PayInfo.prototype.setPayResult = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.zbay);
